/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from "./Migrations";
import { MYDCContract } from "./MYDC";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "MYDC"): MYDCContract;
    }
  }
}

export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { MYDCContract, MYDCInstance } from "./MYDC";
